name       : fb2converter
version    : 1.67.1
release    : 12
source     :
    - https://github.com/rupor-github/fb2converter/archive/refs/tags/v1.67.1.tar.gz : 675ca64b8ac0c8df8ebb5d13eccec98af3bc56d498550164e72d914a03befabe
license    : GPL-3.0-only
component  : office.viewers
summary    : Unified converter of FB2 files into epub2, kepub, mobi and azw3 formats.
description: |
    CLI ebook format converter, a complete rewrite of fb2mobi. Aims to be faster than python implementation and much easier to maintain. Simpler configuration, zero dependencies, better diagnostics and no installation required.
builddeps  :
    - git
    - golang
setup      : |
    export CMAKE_CROSSCOMPILING=false
    export MSYSTEM_NAME=linux_amd64
    %apply_patches
    %cmake 
build      : |
    %make
install    : |
    install -Dm00755 fb2c $installdir/usr/bin/fb2c
