name       : fb2converter
version    : 1.61.2
release    : 2
source     :
    - https://github.com/rupor-github/fb2converter/archive/refs/tags/v1.61.2.tar.gz : 1702a05944c7d5f8cc154ce0e9c62924c8d27ae548b36d42397ad7b86455a223
license    : GPL-3.0-only
component  : office.viewers
summary    : Unified converter of FB2 files into epub2, kepub, mobi and azw3 formats.
description: |
    CLI ebook format converter, a complete rewrite of fb2mobi. Aims to be faster than python implementation and much easier to maintain. Simpler configuration, zero dependencies, better diagnostics and no installation required.
builddeps  :
    - cmake
    - git
    - golang
setup      : |
    export CMAKE_CROSSCOMPILING=false
    export MSYSTEM_NAME=linux_amd64
    %apply_patches
    %cmake 
build      : |
    %make
install    : |
    install -Dm00755 fb2c $installdir/usr/bin/fb2c
