name       : fb2converter
version    : 1.71.0
release    : 14
source     :
    - https://github.com/rupor-github/fb2converter/archive/refs/tags/v1.71.0.tar.gz : 23be09d16943c60e422fc10a61e9f33f82ff257116afec2415f1eca9edd7f444
license    : GPL-3.0-only
component  : office.viewers
summary    : Unified converter of FB2 files into epub2, kepub, mobi and azw3 formats.
description: |
    CLI ebook format converter, a complete rewrite of fb2mobi. Aims to be faster than python implementation and much easier to maintain. Simpler configuration, zero dependencies, better diagnostics and no installation required.
builddeps  :
    - git
    - golang
setup      : |
    export CMAKE_CROSSCOMPILING=false
    export MSYSTEM_NAME=linux_amd64
    %apply_patches
    %cmake 
build      : |
    %make
install    : |
    install -Dm00755 fb2c $installdir/usr/bin/fb2c
